M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, 08 March 2023 at 11:07:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-08T11:07:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X120.66Y-131.9
X126.44Y-131.9
T2
X79.35Y-77.05
X79.35Y-135.15
X155.6Y-77.05
X155.6Y-135.05
T0
M30
