M48
; DRILL file {KiCad (6.0.7-1)-1} date 2023 January 13, Friday 15:06:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-13T15:06:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X120.66Y-131.9
X126.44Y-131.9
T2
X79.35Y-77.05
X79.35Y-135.15
X155.6Y-77.05
X155.6Y-135.05
T0
M30
